[package]
name = "oxidian"
version = "0.1.0"
edition = "2024"

[dependencies]
nucleo = "0.5.0"
notify = "8.2.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2"
tracing = "0.1"
walkdir = "2.5"

tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }

rusqlite = { version = "0.37", optional = true }
serde_json = { version = "1", optional = true }

[features]
sqlite = ["dep:rusqlite", "dep:serde_json"]

[dev-dependencies]
anyhow = "1"
clap = { version = "4.5.49", features = ["derive", "env"] }
tempfile = "3"
